# Generated by Django 4.2.20 on 2025-04-08 23:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(choices=[('nuevo', 'Nuevo ingreso'), ('pareja', 'Plan pareja'), ('convenio', 'Convenio empresa'), ('normal', 'Plan normal')], max_length=50)),
                ('frecuencia', models.CharField(choices=[('3xsemana', '3 veces por semana'), ('todos', 'Todos los días'), ('2xsemana', '2 veces por semana')], max_length=20)),
                ('monto', models.PositiveIntegerField(help_text='Monto en CLP')),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_termino', models.DateField()),
                ('dias_disponibles', models.IntegerField(default=0)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
